homework 1
Roenke/software-design pull request #1
Opened 2016-09-08 20:01 UTC by Roenke

2016-10-11 20:24 UTC, yurii-litvinov requested changes
Мне кажется, одним из последних коммитов Вы удалили диаграмму. А вообще, одно из самых качественных решений пока что.

2016-10-11 20:24 UTC, yurii-litvinov commented on my-shell/src/main/java/com/spbau/bibaev/software/desing/shell/EntryPoint.java
> +package com.spbau.bibaev.software.desing.shell;
desing -> design? :)

2016-10-11 20:24 UTC, yurii-litvinov commented on my-shell/src/main/java/com/spbau/bibaev/software/desing/shell/Environment.java
> +   * @param variable The name of a variable
JavaDoc генерит дефис между именем параметра и описанием, так что если начинать описание с заглавной, получится некрасиво. Хотя, дело вкуса.

2016-10-11 20:24 UTC, yurii-litvinov commented on my-shell/src/main/java/com/spbau/bibaev/software/desing/shell/Environment.java
> +   * @param value    The value of {@code variable}
Выравнивание пробелами плохо, потому что при рефакторинге может привести к каскаду правок, что негативно скажется на диффах и может привести к лишним конфликтам

2016-10-11 20:24 UTC, yurii-litvinov commented on my-shell/src/main/java/com/spbau/bibaev/software/desing/shell/command/CommandArg.java
> +public class CommandArg {
Ему бы тоже неплохо комментарий

2016-10-11 20:24 UTC, yurii-litvinov commented on my-shell/src/main/java/com/spbau/bibaev/software/desing/shell/util/IoStreamUtils.java
> +    while(readCount > 0) {
О, нашёл, к чему придраться --- пробела не хватает :)

2016-10-11 20:24 UTC, yurii-litvinov commented on my-shell/src/test/java/com/spbau/bibaev/software/desing/shell/util/TextUtilTest.java
> +}
Ещё было бы клёво тесты на команды, тесты на пайпы

2016-10-13 09:54 UTC, Roenke commented on my-shell/src/test/java/com/spbau/bibaev/software/desing/shell/util/TextUtilTest.java
> +}
Добавил

2016-10-13 09:54 UTC, Roenke commented on my-shell/src/main/java/com/spbau/bibaev/software/desing/shell/util/IoStreamUtils.java
> +    while(readCount > 0) {
Теперь он есть

2016-10-13 09:54 UTC, Roenke commented on my-shell/src/main/java/com/spbau/bibaev/software/desing/shell/command/CommandArg.java
> +public class CommandArg {
Добавил

2016-10-13 09:54 UTC, Roenke commented on my-shell/src/main/java/com/spbau/bibaev/software/desing/shell/Environment.java
> +   * @param value    The value of {@code variable}
Согласен, исправил

2016-10-13 09:54 UTC, Roenke commented on my-shell/src/main/java/com/spbau/bibaev/software/desing/shell/Environment.java
> +   * @param variable The name of a variable
Действительно, дело вкуса. В стандартной библиотеке c этим тоже до конца не определились

2016-10-13 09:54 UTC, Roenke commented on my-shell/src/main/java/com/spbau/bibaev/software/desing/shell/EntryPoint.java
> +package com.spbau.bibaev.software.desing.shell;
ага :) исправил

2016-11-22 19:39 UTC, yurii-litvinov approved these changes
- по канонам UML от интерфейса не наследуются, а реализуют (рисуется как наследование, только пунктирной линией)
Но вообще, зачтена.

2016-11-22 19:40 UTC, merged