homework 2
Roenke/software-design pull request #2
Opened 2016-10-13 20:30 UTC by Roenke

Add grep command

2016-12-04 21:37 UTC, yurii-litvinov requested changes
- 
```
>grep plugin build.gradle
apply plugin: 'java'
>grep -w plugin build.gradle
grep -w plugin build.gradle
```
И всё, больше шелл на команды не реагирует :) Это при запуске из IDEA, в её консоли.
Поправьте, пожалуйста.

2016-12-07 19:28 UTC, Roenke commented
Потерял else :( исправил, добавил тест

2016-12-09 22:07 UTC, yurii-litvinov commented
Ага, теперь всё ок, зачтена.

2016-12-09 22:07 UTC, yurii-litvinov approved these changes

2016-12-09 22:07 UTC, merged